### ISSUE TITLE
Crashes and occasional hangs when UCheck left open for hours

### ISSUE THREAD

**Issue by stevehoek** [AdliceSoftware/UCheck#23] opened 2023-12-14 18:32 UTC
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

I leave UCheck open all the time.  I have a scheduled scan at 6am.  When I check it in the morning it has either crashed for crashes as soon as I start to interact with it.  I've also seen some hangs at the end of a scan where I have to force close it or it crashes.
I upload the dumps with each unique behavior.

### ucheck-report

Uploaded under my email

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by RonnyTNL** [comment] 2023-12-15 12:16
Hi @stevehoek would be good for the dev to get a memory dump of such crash for easier analysis.

If you'd like to help you can download this sysinternals tool http://live.sysinternals.com/procdump.exe

Create a folder e.g. c:\dumps, place the procdump.exe in there, open an administrative command-box and execute the command below:

c:\dumps\procdump -ma -i c:\dumps\

then reproduce the issue, this should record a memory dump of the crashing process.
If you want you can reset your Just in time debugger

procdump -u

**Comment by Tigzy** [comment] 2023-12-21 08:05
Hi, we have collected a fair amount of crash dumps for (I believe) this issue. 

<img width="843" alt="image" src="https://github.com/AdliceSoftware/UCheck/assets/9531438/aece9da1-9849-44cf-9c82-9ec0125b6a84">

The problem is that it points to a Qt library crash. Any idea why and when this would happen, do you have regular scans launching ? A lot of portable apps ?

**Comment by RonnyTNL** [comment] 2023-12-21 11:48
I can sort of reproduce this, start UCheck as non full-screen application.
Ran 5 scan's with a large set of portables 800+, and when I resized the interface to full screen it crashed.

I'll see if I can reduce some parameters if it still crashes.

**Comment by RonnyTNL** [comment] 2023-12-21 12:09
I'm guessing on memory leak, after repeated scan's with a large set of portable applications you see that every time the scan is ran more memory is allocated until the point that resizing the UI (after the scan is finished) crashes the application.

![image](https://github.com/AdliceSoftware/UCheck/assets/19427356/9830f9fe-d7b4-40a8-b0d5-72d6f50da93d)

**Comment by RonnyTNL** [comment] 2023-12-21 12:25
Looks like it's related/easier reproduced with the portable part as scanning without it does not increase the memory usage enough to trigger the crash.

**Comment by stevehoek** [comment] 2023-12-21 13:44
I have uCheck running as a full screen application, in admin mode.  A scheduled scan happens at 6am EST.  I've submitted several of those crash logs (64 and 32 procs).  Feels like a memory leak.

**Comment by Tigzy** [comment] 2023-12-21 13:49
The crash was reproduced on our end, indeed when repeating scans. The memory leak is probably within Qt Lib. 
We'll try to update to the latest LTS Qt lib see if it has any effect on this. 
EDIT: The crash is not because of this leak, but a Qt issue. Only eating all memory would lead to a crash from a leak.
EDIT2: The leak isn't in Qt, but in UCheck's code.

**Comment by Tigzy** [comment] 2023-12-22 13:11
This is the same bug as: https://bugreports.qt.io/browse/QTBUG-75298
Working on fixing it.

**Comment by Tigzy** [comment] 2023-12-22 14:12
Issue is found. UCheck for some reason reaches the maximum limit of GDI handles. 
https://learn.microsoft.com/en-us/windows/win32/sysinfo/gdi-objects

<img width="597" alt="image" src="https://github.com/AdliceSoftware/UCheck/assets/9531438/597d61f6-baf5-4aa8-85c3-a24698c5cbbd">

**Comment by stevehoek** [comment] 2023-12-22 14:21
Leaks come in all forms, not just memory... resources like handles leak when the are not cleaned up in the code safely.  What language is UCheck written in?

**Comment by Tigzy** [comment] 2023-12-22 15:00
@stevehoek it's written in C++. 
Leak was found, ExtractIconExA call didn't have its DestroyIcon function.
everytime an icon was extracted from a file we were leaking GDI handle (and memory...) 
If tests are good, we'll make a new BETA available later today.

**Comment by Tigzy** [comment] 2023-12-22 17:11
5.2-BETA1 should fix this.

**Comment by RonnyTNL** [comment] 2023-12-23 12:57
Can't reproduce this anymore on this end.
@stevehoek can you confirm?

**Comment by stevehoek** [comment] 2023-12-23 13:33
@RonnyTNL @Tigzy looks good to me so far... thanks for the quick turnaround on the fix!

**Comment by CursonMF** [comment] 2024-01-02 17:48
@stevehoek @RonnyTNL Fixed on [V5.2.0](https://download.adlice.com/UCheck/Changelog.txt)

**Closed as completed by CursonMF** 2024-01-02 17:48 UTC
Labels: bug
