### ISSUE TITLE
Winget Apps Do Not Display Latest Version Number in UCheck 5.4.0.0-BETA1

### ISSUE THREAD

**Issue by ljmacri** [AdliceSoftware/UCheck#43] opened 2024-04-06 12:46 UTC
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

I have a Win 10 Pro v22H2 laptop and am running the latest UCheck v5.4.0.0-BETA (released 05-Apr-2024) from a removable USB stick. This BETA version of UCheck has added support for winget.

When I view the list of installed programs on the Installed tab of UCheck apps now classified as type "Winget" **display the word "winget" in the Latest column in  instead of the latest available version** (see attached image).

![UCheck v5_4_0_0-BETA1  Updates Latest for Winget Programs Version Missing 05 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/ec668a40-04ca-46a1-9122-9bbd27a5de26)

------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4170 * Firefox v124.0.2 * Microsoft Defender v4.18.24020.7-1.1.24030.4 * Malwarebytes Premium v4.6.12.323-1.0.2309 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0-BETA1

### ucheck-report

The attached .txt files are my latest UCheck v5.4.0.0-BETA scan and debug logs for today's 06-Apr-2024 scan.

[UCheck v5_4_0_0-BETA1 Scan Log 06 Apr 2025.txt](https://github.com/AdliceSoftware/UCheck/files/14893559/UCheck.v5_4_0_0-BETA1.Scan.Log.06.Apr.2025.txt)
[UCheck v5_4_0_0-BETA1 Debug Log 06 Apr 2025.txt](https://github.com/AdliceSoftware/UCheck/files/14893561/UCheck.v5_4_0_0-BETA1.Debug.Log.06.Apr.2025.txt)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by ljmacri** [comment] 2024-04-06 18:42
Further to my original post, if I run the command **winget upgrade** in an elevated command prompt to list the programs installed on my computer that are supported by winget and require an update it shows that a v**3.7.2204.15001** update is available for my current Windows PC Health Check **v3.6.2204.08001** app ...

![WIn 10 Pro v22H2 Command Prompt winget_upgrade for WIndows PC Health Check 06 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/33382706-e88d-4f85-baa5-9ea666443085)

... but UCheck v5.4.0.0-BETA1 reports the latest available version is "winget".

![UCheck v5_4_0_0-BETA1 Windows PC Health Check Winget Version Missing 06 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/7a300aff-d7bf-4b4e-8c9d-f2d2941f0da4)

I have attached new UCheck scan and debug logs since Windows PC Health Check was excluded at History & Settings | Exclusions in my previous UCheck scans.

[UCheck v5_4_0_0-BETA1 2nd Scan Log 06 Apr 2025.txt](https://github.com/AdliceSoftware/UCheck/files/14894657/UCheck.v5_4_0_0-BETA1.2nd.Scan.Log.06.Apr.2025.txt)
[UCheck v5_4_0_0-BETA1 2nd Debug Log 06 Apr 2025.txt](https://github.com/AdliceSoftware/UCheck/files/14894658/UCheck.v5_4_0_0-BETA1.2nd.Debug.Log.06.Apr.2025.txt)

--------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4170 * Firefox v124.0.2 * Microsoft Defender v4.18.24020.7-1.1.24030.4 * Malwarebytes Premium v4.6.12.323-1.0.2309 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0-BETA1

**Comment by Tigzy** [comment] 2024-04-08 10:11
This is a parsing issue. Could you run this command and send me the file ? 
`winget.exe list --disable-interactivity >> out.txt`

**Comment by ljmacri** [comment] 2024-04-08 12:47
Hi @Tigzy  

The attached out.txt file is the requested output from the **winget.exe list** command:

[out.txt](https://github.com/AdliceSoftware/UCheck/files/14905541/out.txt)

**Comment by Tigzy** [comment] 2024-04-08 13:14
Ok thanks, we'll fix that. 
The problem in that output is that the "Available" columns is missing. Do you know if it's because everything is up-to-date ?

**Comment by Tigzy** [comment] 2024-04-08 13:17
Bug referenced here: https://github.com/microsoft/winget-cli/issues/2396
It looks like this happens when no update is available from the list. In our case, we'll consider parsing cannot be done and bail.

**Comment by ljmacri** [comment] 2024-04-08 15:03
> Bug referenced here: [microsoft/winget-cli#2396](https://github.com/microsoft/winget-cli/issues/2396) It looks like this happens when no update is available from the list. In our case, we'll consider parsing cannot be done and bail.

Hi @Tigzy 

The first image I inserted in my 06-Apr-2024 post <[above](https://github.com/AdliceSoftware/UCheck/issues/43#issuecomment-2041164208)> shows the command **winget upgrade** currently finds **4 available updates** for my installed programs.  _Note that this command dos not actually install available updates - you would need to run the command **winget upgrade --all** to apply all available updates_.

![Win 10 Pro v22H2 Command Prompt winget_upgrade for Malwarebyts 08 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/727ed3bf-62f5-41d5-acc2-e539364eb465)

Note that the winget detection for a Malwarerytes v4.6.12.399 update is an **erroneous detection** - this is the version number of the latest MBSetup.exe installer, not the latest Malwarbytes v4.6.12.323 program. See my 25-Mar-2024 post in 1PW's [_What's the conventional version number of the mb4_offline installer?_](https://forums.malwarebytes.com/topic/299077-whats-the-conventional-version-number-of-the-mb4_offline-installer/?do=findComment&comment=1625893) for more information.

I'm personally not a big fan of adding winget detections to UCheck.  I do not use UCheck to install or update "Compatible" (or "Winget") apps, so my main concern is that UCheck quickly and correctly identify available updates. Changing some "Community" apps to "Winget" apps just makes the scan slower, adds more colour coding in the UCheck interface, and makes the GUI more cluttered and confusing than it already is.

**Comment by Tigzy** [comment] 2024-04-08 15:14
FYI, Winget can be disabled in Scan settings.

**Comment by ljmacri** [comment] 2024-04-08 15:59
Hi @Tigzy 

I updated to the latest UCheck v5.4.0..0-**BETA2** (released 08-Apr-2024) and now all the apps previously classified as type "Winget" in v5.4.0.0-BETA1 (e.g., Windows PC Health Check, Belarc Advisor, Intel Driver & SupportAssistant, etc. - see my image <[above](https://github.com/AdliceSoftware/UCheck/issues/43#issue-2229228052)>) have reverted back to "Community"apps.

![UCheck v5_4_0_0-BETA2 All Previous Winget Apps Now Community 08 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/e5fb0699-2740-4852-a2a4-23bf182e85ea)

That includes the outdated Windows PC Health Check app I mentioned in my 06-Apr-2024 post <[above](https://github.com/AdliceSoftware/UCheck/issues/43#issuecomment-2041164208)>.

![UCheck v5_4_0_0-BETA2 Windows PC Health Check Oudated 08 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/47386be5-17c4-433f-9534-0923e541de12)

I checked my setting at History & Settings | **Scan Settings** and confirmed that the Winget option is enabled.

Here are my latest scan and debug logs.

[UCheck v5_4_0_0-BETA2 Scan Log 08 Apr 2023.txt](https://github.com/AdliceSoftware/UCheck/files/14908047/UCheck.v5_4_0_0-BETA2.Scan.Log.08.Apr.2023.txt)
[UCheck v5_4_0_0-BETA2 Debug Log 08 Apr 2023.txt](https://github.com/AdliceSoftware/UCheck/files/14908048/UCheck.v5_4_0_0-BETA2.Debug.Log.08.Apr.2023.txt)

---------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4170 * Firefox v124.0.2 * Microsoft Defender v4.18.24020.7-1.1.24030.4 * Malwarebytes Premium v4.6.12.323-1.0.2309 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0-BETA2

**Comment by ljmacri** [comment] 2024-04-09 12:43
Hi @Tigzy 

I don't know if this helps, but per your 09-Apr-2024 post # 1441 in the Wilders Security topic [_UCheck - Update Your Software in 2 Clicks_](https://www.wilderssecurity.com/threads/ucheck-update-your-software-in-2-clicks.404593/page-58#post-3190591) here's what I see in my Windows registry at HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\winget.exe for my current Windows Package Manager Source (winget) v2024.408.2349.153 app.

![Win 10 Pro v22H2 regedit HKCU App Paths Winget_exe 09 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/dbac2a31-46c1-4401-8287-7c98b4875630)

I have **not** installed Marti Climet's [WingetUI](https://www.marticliment.com/wingetui/) and I know nothing about "custom" versions of winget so I assume I have the "regular" version of winget that was installed from the Microsoft Store the first time I ran a winget command in a Command Prompt on my Win 10 machine.

![Win 10 Pro v22H2 Apps and Features Winget v2024_408_2349_153 09 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/856cac36-a3df-4ef7-9864-82bef624b679)
---------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4170 * Firefox v124.0.2 * Microsoft Defender v4.18.24020.7-1.1.24030.4 * Malwarebytes Premium v4.6.12.323-1.0.2309 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0-BETA2

**Comment by ljmacri** [comment] 2024-04-13 23:44
Hi @Tigzy 

I'm still using UCheck v5.4.0.0-BETA2 and my scan today (13-Apr-2024) **correctly parsed** the Latest version for my Winget apps.

![UCheck v5_4_0_0-BETA1 Installed Tab Winget Programs Latest Version Correct 13 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/c24b3d99-51cc-483d-96e9-7ec8086d1a83)

![UCheck v5_4_0_0-BETA1 Updates Tab Winget Programs Latetst Version Correct 13 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/466911e4-5227-4298-becb-e549ed5744a7)

Here are my latest scan and debug logs.

[UCheck v5_4_0_0-BETA2 Scan Log 13 Apr 2023.txt](https://github.com/AdliceSoftware/UCheck/files/14968952/UCheck.v5_4_0_0-BETA2.Scan.Log.13.Apr.2023.txt)
[UCheck v5_4_0_0-BETA2 Debug Log 13 Apr 2023.txt](https://github.com/AdliceSoftware/UCheck/files/14968953/UCheck.v5_4_0_0-BETA2.Debug.Log.13.Apr.2023.txt)

-------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4291 * Firefox v124.0.2 * Microsoft Defender v4.18.24030.9-1.1.24030.4 * Malwarebytes Premium v4.6.12.323-1.0.2309 * Macrium Reflect Free v8.0.7783 * * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0-BETA2

**Comment by ljmacri** [comment] 2024-04-14 13:06
Hi @Tigzy 

... and as of today (14-Apr-2024) all the apps that were classified yesterday as type "Winget" in v5.4.0.0-BETA2 (e.g., Windows PC Health Check, Belarc Advisor, Intel Driver & SupportAssistant, etc. - see my 13-Apr-2024 post <[above](https://github.com/AdliceSoftware/UCheck/issues/43#issuecomment-2053802553)>) have once again reverted back to "Community"apps.

Due to the erratic behaviour of UCheck v5.4.0.0-BETA2, I'm going to stop posting status updates in this bug report until I hear back from you that you've made a change that you'd like me to test or until you release a new BETA.

![UCheck v5_4_0_0-BETA2 Updates Tab Winget Programs Now Community 14 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/7f5cc254-314d-46a8-bd60-51398ac4036d)

----------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4291 * Firefox v124.0.2 * Microsoft Defender v4.18.24030.9-1.1.24030.4 * Malwarebytes Premium v4.6.12.323-1.0.2309 * Macrium Reflect Free v8.0.7783 * * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0-BETA2

**Comment by Tigzy** [comment] 2024-04-15 10:12
thanks for the feedback. We'll see but I believe this is fixed in the next BETA.

**Comment by ljmacri** [comment] 2024-04-15 19:45
Hi @Tigzy  

I have now updated to the latest UCheck v5.4.0.0-**BETA3** (released 15-Apr-2024) that I am running from a removable USB stick.

"Winget" apps are parsing correctly on the Updates tab and UCheck v5.4.0.0-BETA3 is currently recommending updates for three applications supported by winget [Windows PC Health Check, Microsoft Visual C++ 2015-2022 Redistributable (x64) and Microsoft Visual C++ 2015-2022 Redistributable (x86)] ...

![UCheck v5_4_0_0-BETA3 Updates Tab Three Winget Apps Outdated 15 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/3b5c62dc-db4b-41c1-b933-8d2487fff98c)

... which are the same three apps that the command **winget upgrade** also detects as outdated.

![Win 10 Pro v22H2 Command Prompt winget_upgrade Three Updates Found 15 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/88988b6f-c44d-49d1-92b7-50469922b386)

However, several other apps that are supported by winget that are up-to-date and were **previously identified as "Winget" apps** in UCheck v5.4.0.0-BETA1 (e.g., **Belarc Advisor, Intel Driver & Support Assistant**, etc. - see my original image <[above](https://github.com/AdliceSoftware/UCheck/issues/43#issue-2229228052)>) are **now classified as "Community" apps**.

![UCheck v5_4_0_0-BETA3 Installed Tab Some Winget Apps Now Community 15 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/54366293-3cac-4711-8d88-072ffdaf951a)

**I am not sure if this is a bug or expected behavior.**  Should users expect that that apps supported by winget like Belarc Advisor and Intel Driver & Support Assistant will be classified as "Community" apps if they are up-to-date and then change to a"Winget" app if an update is available?

Here are my latest scan and debug logs plus output from the command **winget list**.

[UCheck v5_4_0_0-BETA3 Scan Log 15 Apr 2023.txt](https://github.com/AdliceSoftware/UCheck/files/14983548/UCheck.v5_4_0_0-BETA3.Scan.Log.15.Apr.2023.txt)
[UCheck v5_4_0_0-BETA3 Debug Log 15 Apr 2023.txt](https://github.com/AdliceSoftware/UCheck/files/14983553/UCheck.v5_4_0_0-BETA3.Debug.Log.15.Apr.2023.txt)
[wingetlist 15 Apr 2024.txt](https://github.com/AdliceSoftware/UCheck/files/14983556/wingetlist.15.Apr.2024.txt)

----------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4291 * Firefox v124.0.2 * Microsoft Defender v4.18.24030.9-1.1.24030.4 * Malwarebytes Premium v4.6.12.323-1.0.2309 * Macrium Reflect Free v8.0.7783 * * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0-BETA3

**Comment by Tigzy** [comment] 2024-04-16 07:06
Hi, this is the expected behavior because the "list" command isn't giving very good results. We had to use the "upgrade" command which unfortunately doesn't tell which ones are up-to-date.

**Comment by Tigzy** [comment] 2024-04-16 07:08
Maybe we can run 2 rounds, upgrade first and then list...

**Comment by Tigzy** [comment] 2024-04-19 09:28
Is this better in the latest BETA ?

**Comment by ljmacri** [comment] 2024-04-19 15:19
BETA4 appears to have more problems than BETA3.

I am currently using UCheck v5.4.0.0-**BETA4** (rel. 19-Apr-2024) and all my installed apps previously classified as "Community" are now classified as "Winget".  Are you certain that winget actually supports all these "Winget" apps (i.e., that winget can be used to install updates for all apps now classified as "Winget")?

![UCheck v5_4_0_0-BETA4 Installed Tab All Community Now Winget 19 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/cb47a6e0-47fd-4d31-8278-7b0de93d93f0)

According to the 14-Sep-2023 winget discussion at [_How to find out which installed Apps can be updated by winget and which cannot_](https://github.com/microsoft/winget-cli/discussions/3624#discussioncomment-7035377), when you run the winget list command and look at the **ID column** then **Microsoft Store UWP apps** (e.g., ID = Microsoft.WindowsAlarms_8wekyb3d8bbwe) and **apps with a GUID** in the ID column [e.g., ID = {00001220-0220-1033-84C8-B8D95FA3C8C3}]  **cannot be updated by winget**. I know very little about winget so I cannot confirm if this is true or not.

The attached file named wingetlist_short_19_Apr_2024.txt was created by running the command **winget list | sort >"%userprofile%\Desktop\wingetlist_short_19_Apr_2024.txt"**.  That text file was then edited to remove all Microsoft Store UWP apps so that it only includes the ~ 50 programs installed on my system that are also listed at Control Panel | Programs | Programs and Features. About **20 of those 50 installed programs** (e.g., Apple Software Updater, Dell Update for Windows Universal, Epson Print CD, etc.) listed in the edited text file that I have attached below **have a GUID in the ID column**, which suggests they cannot be updated by winget and **should still be classified as "Community" apps** rather than "Winget" apps.

[wingetlist_short_19_Apr_2024.txt](https://github.com/AdliceSoftware/UCheck/files/15041986/wingetlist_short_19_Apr_2024.txt)
[UCheck v5_4_0_0-BETA4 Scan Log 19 Apr 2023.txt](https://github.com/AdliceSoftware/UCheck/files/15041990/UCheck.v5_4_0_0-BETA4.Scan.Log.19.Apr.2023.txt)
[UCheck v5_4_0_0-BETA4 Debug Log 19 Apr 2023.txt](https://github.com/AdliceSoftware/UCheck/files/15041994/UCheck.v5_4_0_0-BETA4.Debug.Log.19.Apr.2023.txt)

Right now **I cannot tell you if the BETA4 is working correctly** because I do not have any apps classified as "Winget" with a GUID as their ID that currently require an update.
________________________________________

Just FYI, the UCheck v5.4.0.0-BETA4 Updates tab still correctly recommends updates for three applications supported by winget [Windows PC Health Check, Microsoft Visual C++ 2015-2022 Redistributable (x64) and Microsoft Visual C++ 2015-2022 Redistributable (x86)], which are the same three apps that the command **winget upgrade** also detects as outdated.

![UCheck v5_4_0_0-BETA4 Updates Tab Three Winget Apps Outdated 19 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/f95d06ef-fd34-4122-a081-53b74618598a)
 
![Win 10 Pro v22H2 Command Prompt winget_upgrade Three Updates Found 19 Apr 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/ad9b065c-a3cf-40d2-800f-7a70bada89b8)

-------------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4291 * Firefox v125.0.1 * Microsoft Defender v4.18.24030.9-1.1.24030.4 * Malwarebytes Premium v4.6.12.323-1.0.2309 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0-BETA4

**Comment by Tigzy** [comment] 2024-05-07 08:01
Thanks, actually the easiest is to lookup at the source. If it's empty then we should not take it into account. 
We'll fix that in the next version.

**Comment by ljmacri** [comment] 2024-05-09 15:20
> Thanks, actually the easiest is to lookup at the source. If it's empty then we should not take it into account. ...

Hi @Tigzy 

Yes, that might be the best way to check. 

I ran a **winget list** command today (winget list | sort >"%userprofile%\Desktop\wingetlist.txt") and then manually moved the applications where the Source column is empty down to the bottom of the list.  The attached .txt file shows that all the Microsoft Store UWP apps (e.g., ID = Microsoft.WindowsAlarms_8wekyb3d8bbwe) or apps with a GUID in the ID column [e.g., ID = {00001220-0220-1033-84C8-B8D95FA3C8C3}] that supposedly cannot be updated by winget **do not say "winget" in the Source column**.

[wingetlist 09 May 2024.txt](https://github.com/AdliceSoftware/UCheck/files/15264077/wingetlist.09.May.2024.txt)

----------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4291 * Firefox v125.0.3 * Microsoft Defender v4.18.24030.9-1.1.24040.1 * Malwarebytes Premium v5.1.3.110-1.0.1219 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0-BETA4

**Comment by ljmacri** [comment] 2024-05-13 23:14
Hi @Tigzy:

I just realized that a stable version of UCheck v5.4.0.0 has been available for testing for almost week now.

I have now updated to the latest stable release of **UCheck v5.4.0.0 (rel. 07-May-2024)** that I am running from a removable USB stick. Here are my latest scan and debug logs:

[UCheck v5_4_0_0 Scan Log 13 May 2024.txt](https://github.com/AdliceSoftware/UCheck/files/15300606/UCheck.v5_4_0_0.Scan.Log.13.May.2024.txt)
[UCheck v5_4_0_0 Debug Log 13 May 2024.txt](https://github.com/AdliceSoftware/UCheck/files/15300607/UCheck.v5_4_0_0.Debug.Log.13.May.2024.txt)

In general, the Installed tab looks much better and the stable build does a better job of distinguishing "Winget" versus "Community" apps.

![UCheck v5_4_0_0  Community Apps Visible 13 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/6cf4d704-06bd-4707-8c89-599aaeea0867)

However, here are **three problems** I noticed for UCheck v5.4.0.0 (stable):

1. I am once again seeing an **erroneous detection for a Preview build MS Office 2019 C2R**.  UCheck is recommending an Insiders Preview Version 2405 / Build 17628.2006 (rel. 06-May-2024 - see the update history at https://learn.microsoft.com/en-us/officeupdates/update-history-current-channel-preview) when it should be recommending the latest stable Current Channel Version 2404 / Build 17531.20140 (rel. 07-May-2024 - see the release notes at https://learn.microsoft.com/en-us/officeupdates/current-channel).

![UCheck v5_4_0_0 Erronous Detection of MS Office 2019 Insider v2405 Build 17628_20006 13 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/dfb6e8cb-bad8-4fa7-a73b-5316d2f45818)

2.  **TreeSize Free Portable** v4.7.3.550 was released 07-May-2024 (see the release notes at https://www.jam-software.com/treesize_free/changes.shtml) but UCheck is still recommending the previous v4.7.2.526 (rel. 29-Feb-2024).

![UCheck v5_4_0_0 TreeSize Free Portable v4_7_3_550 Not Detected 13 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/3b2c135b-8275-4895-b838-63a7cfd9c0c1)

3.  UCheck is incorrectly classifying **Microsoft Edge Update** as a "Winget" app and incorrectly detecting the "Latest" version as v124.0.2478.97 when it should be v1.3.187.37.

![Win 10 Pro v22H2 File Explorer Program_Files_x86 MicrosoftEdgeUpdate_exe v1_3_187_37 13 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/e4909bd9-a6cb-4c08-beee-c6182cc87710)

Here is what **winget list** and **winget upgrade** show (i.e., the **Source column is blank** for Microsoft Edge Update):

[wingetlist 13 May 2024.txt](https://github.com/AdliceSoftware/UCheck/files/15300666/wingetlist.13.May.2024.txt)

![Win 10 Pro v22H2 Command Prompt winget_upgrade Three Updates Found 13 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/2723af9a-b82e-4e0a-b125-5ad901691cfc)

Here is what UCheck displays if History & Settings | Scan Settings | **Winget is ENABLED** (i..e, "Latest" available version **124.0.2478.97 is incorrect**; I also don't know why the **"Status" is not Outdated** when 124.0.2478.97 is greater than1.3.187.37 ) ...

![UCheck v5_4_0_0 Microsoft Edge Update v124_0_2478_97 Wrong Version 13 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/ff72eb64-f4eb-44f3-a699-040da22b64dd)

... and here is what UCheck displays if History & Settings | Scan Settings | **Winget is DISABLED** (i.e., Microsoft Edge Update is ignored by UCheck).   See the 17-May-2024 Issue https://github.com/AdliceSoftware/UCheck/issues/50 for additional details.

![UCheck v5_4_0_0 Winget Scan OFF Microsoft Edge Update Not Displayed 13 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/06be330b-7747-4578-855c-edfa74f3ea7b)

------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4291 * Firefox v125.0.3 * Microsoft Edge v124.0.2478.97 * Microsoft Defender v4.18.24030.9-1.1.24040.1 * Microsoft Office Home and Business 2019 Click-to-Run v2404 (Build 17531.20140) * Malwarebytes Premium v 5.1.4.112-1.0.1233 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.4.0.0 (stable)

**Comment by Tigzy** [comment] 2024-06-03 10:20
I'm closing this defect as I think most of the problems were now resolved. Please re-open or create a new defect if you find more issues

**Closed as completed by Tigzy** 2024-06-03 10:20 UTC
Labels: bug
